[package]
name = "kernel_tracer"
version.workspace = true
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spin.workspace = true
compact_str.workspace = true
slab = { version = "0.4", default-features = false }
drivers = { path = "../../drivers" }
sbi_console = { path = "../../arch/sbi_console" }
anstyle = { version = "1.0", default-features = false }
