[package]
name = "kernel"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
riscv.workspace = true
compact_str.workspace = true
goblin.workspace = true
bitflags.workspace = true
sbi-rt.workspace = true
pin-project.workspace = true
riscv_time = { path = "../arch/riscv_time" }
drivers_hal = { path = "../drivers/drivers_hal" }
executor = { path = "../executor" }
memory = { path = "../memory" }
filesystem = { path = "../filesystem" }
idallocator = { path = "../utils/idallocator" }
defines = { path = "../utils/defines" }
kernel_tracer = { path = "../utils/kernel_tracer" }
klocks = { path = "../utils/klocks" }
uart_console = { path = "../utils/uart_console" }
crossbeam-utils = { version = "0.8", default-features = false }
anstyle = { version = "1.0", default-features = false }

[features]
default = []
# 是否使用 `span` 进行性能分析
profiling = ["kernel_tracer/profiling"]
ktest = []

[lints]
workspace = true
