[package]
name = "kernel"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
atomic.workspace = true
bytemuck.workspace = true
riscv.workspace = true
compact_str.workspace = true
goblin.workspace = true
bitflags.workspace = true
sbi-rt.workspace = true
pin-project.workspace = true
event-listener.workspace = true
triomphe.workspace = true
extend.workspace = true
riscv_time = { path = "../arch/riscv_time" }
riscv_guard = { path = "../arch/riscv_guard" }
user_check = { path = "../arch/user_check" }
drivers = { path = "../drivers/drivers" }
executor = { path = "../executor" }
memory = { path = "../memory" }
filesystem = { path = "../filesystem" }
idallocator = { path = "../utils/idallocator" }
defines = { path = "../utils/defines" }
kernel_tracer = { path = "../utils/kernel_tracer" }
klocks = { path = "../utils/klocks" }
uart_console = { path = "../utils/uart_console" }
macros = { path = "../utils/macros" }
crossbeam-utils = { version = "0.8", default-features = false }
anstyle = { version = "1.0", default-features = false }
slab = { version = "0.4", default-features = false }

[features]
default = []
# 是否使用 `span` 进行性能分析
profiling = []
ktest = []

[lints]
workspace = true
