[package]
name = "kernel"
version.workspace = true
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log.workspace = true
spin.workspace = true
riscv.workspace = true
compact_str.workspace = true
goblin.workspace = true
bitflags.workspace = true
sbi-rt.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
riscv_time = { path = "../arch/riscv_time" }
sbi_console = { path = "../arch/sbi_console" }
executor = { path = "../executor" }
memory = { path = "../memory" }
idallocator = { path = "../utils/idallocator" }
simple_logger = { path = "../utils/simple_logger" }
defines = { path = "../utils/defines" }
drivers = { path = "../drivers" }
unwinding = { version = "0.2", default_features = false, features = [
  "unwinder",
  "fde-static",
  "personality",
  "panic",
], optional = true }
pin-project = "1.1"

[features]
default = ["unwinding"]
