[package]
name = "kernel"
version.workspace = true
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spin.workspace = true
riscv.workspace = true
compact_str.workspace = true
goblin.workspace = true
bitflags.workspace = true
sbi-rt.workspace = true
pin-project.workspace = true
riscv_time = { path = "../arch/riscv_time" }
sbi_console = { path = "../arch/sbi_console" }
executor = { path = "../executor" }
memory = { path = "../memory" }
idallocator = { path = "../utils/idallocator" }
defines = { path = "../utils/defines" }
drivers = { path = "../drivers" }
kernel_tracer = { path = "../utils/kernel_tracer" }

[lints]
workspace = true
