[package]
name = "xtask"
version.workspace = true
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fatfs.workspace = true
tap.workspace = true
scopeguard.workspace = true
clap = { version = "4.5", features = ["derive"] }
const_format = "0.2"
chrono = "0.4"
fastrand = "2.0"
serde_json = "1.0"
anyhow = "1.0"

[lints]
workspace = true
