[package]
name = "xtask"
version.workspace = true
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fatfs.workspace = true
tap.workspace = true
clap = { version = "4.3", features = ["derive"] }
const_format = "0.2"
chrono = "0.4"
