[alias]
xtask = "run --package xtask --target-dir xtask/target --"
xbuild = "xtask build"
xclean = "xtask clean"
asm = "xtask asm"
qemu = "xtask qemu"
env = "xtask env"
lint = "xtask lint"
ktest = "xtask ktest"
profiling = "xtask profiling"
