[package]
name = "executor"
version.workspace = true
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log.workspace = true
spin.workspace = true
defines = { path = "../utils/defines" }
async-task = { version = "4.5", default-features = false }
crossbeam-queue = { version = "0.3", default-features = false, features = [
  "alloc",
] }
