[package]
name = "qemu_block"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
memory = { path = "../../memory" }
defines = { path = "../../utils/defines" }
klocks = { path = "../../utils/klocks" }
virtio-drivers = "0.7"

[lints]
workspace = true
