[package]
name = "signal"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
num_enum.workspace = true
defines = { path = "../utils/defines" }

[lints]
workspace = true
